export {default as Navbar} from './Navbar'
export {default as Blog} from './Blog'
export {default as Home} from './Home'
export {default as About } from './About'
export {default as Detail } from './Detail'
export {default as PageNotFound } from './PageNotFound'